---
title: "Eq's and params"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(magrittr)
library(knitr)
library(here)
```

Equations

$$
\begin{aligned}
 \frac{dS_a}{dt} &= -\beta_a S_a I_a - \beta_b S_a I_b - \phi S_aV + \lambda_a - \mu_a S_a \\ \\
 \frac{dS_b}{dt} &= -\beta_b S_b I_b - \beta_a S_b I_a - \phi S_bV + \lambda_b - \mu_b S_b \\ \\
 \frac{dI_a}{dt} &= \beta_a S_a I_a + \beta_b S_a I_b + \phi S_aV - \alpha_a I_a - \mu I_a \\ \\
 \frac{dI_b}{dt} &= \beta_b S_b I_b + \beta_a S_b I_a + \phi S_bV - \alpha_b I_b - \mu I_b \\ \\
 \frac{dR_a}{dt} &= \alpha_a I_a - \mu_a R_a\\ \\
 \frac{dR_b}{dt} &= \alpha_b I_b - \mu_b R_b\\ \\
 \frac{dV}{dt} &= \sigma_a I_a + \sigma_b I_b - \epsilon V\\ \\
\end{aligned}
$$

```{r}
# mat[1] = (data$trans1[n]*data$dfe1[n])/(data$reco1[n]+data$mort1[n])
# mat[2] = (data$trans1[n]*data$dfe2[n])/(data$reco2[n]+data$mort2[n])
# mat[3] = (data$shed1[n]/data$degr[n])
# mat[4] = (data$trans2[n]*data$dfe1[n])/(data$reco1[n]+data$mort1[n])
# mat[5] = (data$trans2[n]*data$dfe2[n])/(data$reco2[n]+data$mort2[n])
# mat[6] = (data$shed2[n]/data$degr[n])
# mat[7] = (data$trans3[n]*data$dfe1[n])/(data$reco1[n]+data$mort1[n])
# mat[8] = (data$trans3[n]*data$dfe2[n])/(data$reco2[n]+data$mort2[n])
# mat[9] = 0
```



$$
\begin{bmatrix}
\frac{\beta_a\frac{\lambda_a}{\mu_a}}{\alpha_a+\mu_a} & \frac{\beta_a\frac{\lambda_b}{\mu_b}}{\alpha_b+\mu_b} & \frac{\sigma_a}{\epsilon}\\
\frac{\beta_b\frac{\lambda_a}{\mu_a}}{\alpha_a+\mu_a} & \frac{\beta_b\frac{\lambda_b}{\mu_b}}{\alpha_b+\mu_b} & \frac{\sigma_b}{\epsilon}\\
\frac{\phi\frac{\lambda_a}{\mu_a}}{\alpha_a+\mu_a} & \frac{\phi\frac{\lambda_b}{\mu_b}}{\alpha_b+\mu_b} & 0\\
\end{bmatrix}
$$






Parameters


$$
\begin{align*}
 & \beta_a = transmission\ rate\ for\ highly\ competent\\ \\
 & \beta_b = transmission\ rate\ for\ less\ competent\\ \\ 
 & \phi = environmental\ transmission\ rate\\ \\ 
 & \lambda = birth\ rate\\ \\ 
 & \mu_a = death\ rate\\ \\
 & \mu_b = death\ rate\\ \\
 & \alpha = recovery\ rate\\ \\
 & \sigma = shedding\ rate\\ \\
 & \epsilon = viral\ degradation\ rate\\ \\
 \\ \\
 & S = \text{Susceptible individuals}\\ \\
 & I = \text{Infectious individuals}\\ \\
 & R = \text{Recovered individuals}\\ \\
 & V = \text{free-living infectious virions}\\ \\
\end{align*}
$$

```{r}
Parameter <- c("$\\beta_a$","$\\beta_b$","$\\phi$","$\\lambda$","$\\mu$","$\\alpha$","$\\sigma$","$\\epsilon$")
Description <- c("transmission rate for highly competent","transmission rate for less competent",
                 "environmental transmission rate", "birth rate", "death rate", "recovery rate",
                 "shedding rate", "viral degradation rate")
param_table <- tibble(Parameter, Description)
kable(param_table)
```

```{r}
# library(metacom)
# 
# source(knitr::purl(here("scripts/data_format.Rmd"), quiet=TRUE))
# 
# community_mat %<>% column_to_rownames(., var = "siteID")
# 
# Imagine(t(community_mat), 
#         fill = FALSE, 
#         order = TRUE, 
#         xlab = "", 
#         ylab = "",
#         xline = 5,
#         yline = 4,
#         sitenames = ,
#         speciesnames = ,
#         binary=T)
# 
# ordered_matrix <- OrderMatrix(community_mat)
# rownames(ordered_matrix)
# 
# results <- Metacommunity(community_mat, binary = T)
# coherence <- results$Coherence
# turnover <- results$Turnover
# boundary <- results$Boundary
# kable(coherence, caption = "Coherence")
# kable(turnover, caption = "Turnover")
# kable(boundary, caption = "Block Replacement")

```


