---
title: "sensitivity"
author: "Daniel Suh"
date: "`r Sys.Date()`"
output: html_document
---

```{r library, message = F}
library(tidyverse)
library(magrittr)
#install_github("thomasp85/patchwork")
library(patchwork)
library(ggnewscale)
library(here)
library(deSolve)
library(lhs)
```

```{r model}
rm0<-function(t,x,params){
  Sa <- x[1]  
  Ia <- x[2]
  Ra <- x[3]
  Sb <- x[4]  
  Ib <- x[5]
  Rb <- x[6]
  V <- x[7]
  with(as.list(params),{
    dSa <- -beta*Sa*Ia - betab*Sa*Ib - phi*Sa*V + lambda - mu_a*Sa
    dIa <- beta*Sa*Ia + betab*Sa*Ib + phi*Sa*V - alpha*Ia - mu_a*Ia
    dRa <- alpha*Ia - mu_a*Ra
    
    dSb <- -betab*Sb*Ib - beta*Sb*Ia - phi*Sb*V + lambda - mu_b*Sb
    dIb <- betab*Sb*Ib + beta*Sb*Ia + phi*Sb*V - alpha*Ib - mu_b*Ib
    dRb <- alpha*Ib - mu_b*Rb
    
    dV <- sigma*Ia + sigma*Ib - epsilon*V
    res<-c(dSa,dIa,dRa,dSb,dIb,dRb,dV)
    list(res)
  })}
#no demography
rm1<-function(t,x,params){
  Sa <- x[1]  
  Ia <- x[2]
  Ra <- x[3]
  Sb <- x[4]  
  Ib <- x[5]
  Rb <- x[6]
  V <- x[7]
  with(as.list(params),{
    dSa <- -beta*Sa*Ia - betab*Sa*Ib - phi*Sa*V
    dIa <- beta*Sa*Ia + betab*Sa*Ib + phi*Sa*V - alpha*Ia
    dRa <- alpha*Ia
    
    dSb <- -betab*Sb*Ib - beta*Sb*Ia - phi*Sb*V
    dIb <- betab*Sb*Ib + beta*Sb*Ia + phi*Sb*V - alpha*Ib
    dRb <- alpha*Ib
    
    dV <- sigma*Ia + sigma*Ib - epsilon*V
    res<-c(dSa,dIa,dRa,dSb,dIb,dRb,dV)
    list(res)
  })}


maxTime <- 300.0 # time is in years - run model for this time
times<-seq(0,maxTime,by=1) # how long we run the model for
# notes on params
# mu =     <- density-independent mortality rate
# beta =       <- contact transmission rate by infected A
# betab =       <- contact transmission rate by infected B
# phi =      <- environmental transmission rate
# lambda =       <- density-dependent growth rate
# alpha =     <- recovery rate
# sigma =    <- shedding rate
# epsilon =       <- viral degradation rate
params<-c(mu_a=1/50,
          mu_b=1/50,
          beta=0.001,
          betab=0.0001,
          phi=0.001,
          lambda=5/3,
          alpha=1/10,
          sigma=1/2,
          epsilon=1/2)  # model parameters

xstart<-c(Sa=116,
          Ia=1,
          Ra=0,
          Sb=83,
          Ib=1,
          Rb=0,
          V=0)  # initial conditions

output<-as.data.frame(lsoda(xstart,times,rm0,params)) # tells computer to solve (integrate) equations
```


```{r lhs}
h <- 1000               #choose number of points
set.seed(8878896)
lhs<-maximinLHS(h,9)   #simulate
```


```{r}
mu_a_min <- 1/50*0.8
mu_a_max <- 1/50*1.2
mu_b_min <- 1/50*0.8
mu_b_max <- 1/50*1.2
beta_min <- 0.001*0.8
beta_max <- 0.001*1.2
betab_min <- 0.0001*0.8
betab_max <- 0.0001*1.2
phi_min <- 0.001*0.8
phi_max <- 0.001*1.2
lambda_min <- 5/3*0.8
lambda_max <- 5/3*1.2
alpha_min <- 1/10*0.8
alpha_max <- 1/10*1.2
sigma_min <- 1/2*0.8
sigma_max <- 1/2*1.2
epsilon_min <- 1/2*0.8
epsilon_max <- 1/2*1.2


params.set <- cbind(
  mu_a <- lhs[,1]*(mu_a_max - mu_a_min) + mu_a_min,
  mu_b <- lhs[,2]*(mu_b_max - mu_b_min) + mu_b_min,
  beta <- lhs[,3]*(beta_max - beta_min) + beta_min,
  betab <- lhs[,4]*(betab_max - betab_min) + betab_min,
  phi <- lhs[,5]*(phi_max - phi_min) + phi_min,
  lambda <- lhs[,6]*(lambda_max - lambda_min) + lambda_min,
  alpha <- lhs[,7]*(alpha_max - alpha_min) + alpha_min,
  sigma <- lhs[,8]*(sigma_max - sigma_min) + sigma_min,
  epsilon <- lhs[,9]*(epsilon_max - epsilon_min) + epsilon_min
)

```


```{r}
levels <- 11

h2 <- 250

j <- 1

data <- data.frame(matrix(rep(NA,levels*h2*14),nrow=levels*h2))
for(i in 1:h2){
    
    data[j,1:9] <- as.list(c(params.set[i,]))
    params <- params.set[i,]
    out <- as.data.frame(lsoda(xstart, times, rm0, params))
    data[j,10] <- tail(out$Ia, 1)
    data[k,11] <- tail(out$Ib, 1)s
    j <- j+1
    
}
```




