---
title: "workshop"
author: "Daniel Suh"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---


```{r, message = F}
library(here)

source(here("base","src.R"))

library(reshape2)
```


```{r, message = F}
data <- read_csv(here("data/weighted_prev_competence_111220.csv"))
tree <- ape::read.nexus(here("data/raw_data/asup_just_tree.txt"))
names <- read_csv(here("data/raw_data/species_names_ids.csv"))
```





## Variation in competence for each species

### comparing ranked means with and without log-transformation of raw data

```{r}
vl <- readRDS(here("processed_data","vl.rds"))

supp1_raw <- vl %>% arrange(mean) %>% 
  mutate(abb_name = factor(abb_name, levels = abb_name)) %>% 
  ggplot(.,aes(x=abb_name,y=mean)) +
  geom_point() + 
  xlab("Species") + ylab("Viral Load") + 
  geom_linerange(aes(ymin=mean-se,ymax=mean+se)) +
  geom_hline(yintercept = 1) + 
  labs(title = "Viral Loads") + 
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
  scale_y_continuous(breaks=seq(0,6,1))

supp1_log10 <- vl %>% arrange(mean) %>% 
  mutate(abb_name = factor(abb_name, levels = abb_name)) %>% 
  ggplot(.,aes(x=abb_name,y=log1p_mean)) +
  geom_point() + 
  xlab("Species") + ylab("log1p(Viral Load)") + 
  geom_linerange(aes(ymin=log1p_mean-log1p_se,ymax=log1p_mean+log1p_se)) +
  geom_hline(yintercept = 1) + 
  labs(title = "Viral Loads") + 
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
  scale_y_continuous(breaks=seq(0,6,1))

supp1_raw
supp1_log10
```


```{r}
incidence <- data %>% group_by(WetAltID, Month.1) %>% summarize(incidence = sum(RV.Status))

incidence %>% ggplot(.,aes(x=Month.1, y=incidence)) + geom_col() + facet_grid(vars(WetAltID))
```


```{r}
comm_data <- readRDS(here("processed_data","comm_data.rds"))
comm_data %>% ggplot(.,aes(x=Month.1, y=Prevalence)) + geom_point() + facet_wrap(~WetAltID, nrow = 5, ncol = 4)
```

