---
title: "manuscript"
author: "Daniel Suh"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:   
  pdf_document: default
  word_document:
    reference_docx: rv_ms_081921.docx
bibliography: refs.bib
---

# To do



# Notes

Community composition is a primary driver of epidemics caused by generalist parasites. Dilution effects are an example of community composition influencing parasite transmission and species richness can be predictive of dilution effects when the necessary conditions are present. These conditions include a correlation between relative abundance of hosts, the rarity of hosts, and predictable assembly/disassembly of communities. For example, if host competence correlates positively with relative abundance and if more competent hosts are less likely to be lost as communities disassemble, then species richness can be predictive of parasite transmission via these mechanisms. Another way to understand this relationship is to use community competence as a community-level metric for how competent a community is. When dilution effect conditions exist, community competence will predictably increase as species are lost in a community. However, similar community competence values can be achieved via alternative community compositions that may not follow a dilution effect pattern. If host species still vary in their competence and if there is still a positive correlation between relative abundance and competence BUT if assembly/disassembly does not follow a dilution effect pattern, then species richness is not a useful predictor for parasite transmission but community competence can still be predictive. If assembly/disassembly is random, then high competence communities will exist simply by chance. Alternatively, if there is not a correlation between relative abundance and host competence but there are dilution effect patterns in assembly/disassembly, then species richness is still not useful, but community competence is. In a situation where the rare host is most competent, high species richness communities may be the most competent. Also, if competence is distributed randomly with high variance, then community competence may vary unpredictably with species richness, but community competence can still be predictive of parasite transmission.

* Dilution effects depend on
  + a positive correlation between relative abundance and competence
  + a correlation between relative abundance and assembly pattern
    + i.e. higher relative abundance means less likely to be lost from a community
* Community competence should correlate with species richness if these conditions hold
* Community competence can still be high even if these conditions do not hold
* In empirical data, do we see these dilution effect patterns?
* If we do not see these dilution effect patterns, then are we still able to see high community competence values?
  + What drives these community competence values?
    + Is it a rare but highly competent species, abundant but moderately competent species?
    + How does evenness help to explain community competence?

* Other things to check
  + Variation in competence within species - is competence a robust trait or highly plastic?
  + Variation in qPCR values - how reliable are our estimates?



# Introduction
Most parasites must navigate a complex environment in order to complete their life cycle and are constrained by the availability and suitability of hosts as well as environmental conditions. Generalist parasites contend with changes in the relative and absolute abundance of their various hosts, and parasites that are transmitted environmentally must rely on favorable conditions for persistence until they are taken up by a new host. Much attention has been paid to anthropogenic-induced changes in the biotic and abiotic conditions experienced by parasites, including introduction and extirpation of species, climate warming, pollution, and land conversion [@altizer_climate_2013; @patz_unhealthy_2004; @young_introduced_2017]. Many of these changes feed into the dilution effect hypothesis, which posits that transmission (in general, or relative to a focal host species) is augmented as host species richness declines, often in response to anthropogenic influence [@johnson_why_2015; @keesing_effects_2006]. However, biotic and abiotic change also occurs naturally over time and space. Moreover, the joint effects of abiotic and biotic drivers of epizootics are rarely considered together [@bienentreu_amphibian_2020; @dillon_direct_2019; @hall_why_2010; @north_anthropogenic_2015; @scott-baumann_review_2015], and theoretical prediction for such interaction is underdeveloped. In part, this is due to the notion that transmission is influenced by abiotic factors at large spatial scales and by biotic factors at smaller scales [@halliday_past_2019; @rohr_towards_2019]. However, host mobility often means transmission is occurring at intermediate spatial scales, where communities of hosts are connected, and in these metacommunities, the joint influence of host community structure and environmental conditions on parasite transmission is not well understood. In response to this knowledge gap, we combine theoretical and empirical approaches to study how biotic and abiotic factors interact to promote transmission of ranavirus in amphibian communities. We demonstrate that focusing on the relative abundance of species, in concert with total community size and environmental conditions, provides a more detailed explanation for spatiotemporal variation in outbreak risk that cannot be solely explained by biotic or abiotic variables alone. In addition, we build upon existing theory regarding the relationship between host biodiversity and parasite transmission by demonstrating that host species evenness, rather than richness, can be used to relate community composition to outbreak risk.

Generalist parasites, such as ranaviruses, are commonly found in nature and often use a range of alternative host species to reproduce [@park_characterizing_2018; @poulin_comparative_2011]. The transmission potential of a generalist parasite for a given host species may vary due to differences in host species abundances [@fenton_parasite_2002; @hopkins_systematic_2020], host competence (i.e. the ability for an individual host to become infected and pass infection on to others [@martin_burrows_2019]), and the environmental conditions in which the interaction takes place [@altizer_climate_2013; @cable_global_2017; @rohr_frontiers_2011]. The combination of these factors makes it difficult to assess how multi-species host communities are differentially at risk of parasite invasion and onward transmission to other communities [@johnson_why_2015]. One method to separately quantify the effects of host abundance and competence on parasite transmission is to use community competence: the weighted average of competence values of host species in the community [@johnson_biodiversity_2013]. In addition, community competence is advantageous because it considers the relative abundance of a species rather than the presence of a species alone. For example, a commonly occurring, low-competence host could be responsible for more transmission than a rare, high-competence host [@holt_parasite_2003]. In contrast to host species richness, which is the typical predictor variable in the dilution effect hypothesis literature, community competence and host abundance are more directly related to the parasite basic reproductive number, R0 [@dobson_population_2004; @rohr_towards_2019].

Ranaviruses (genus Ranavirus, family Iridoviridae) are well-suited for studying host-parasite-environment interactions at the community scale and are associated with worldwide amphibian declines, making them a parasite of global concern [@lesbarreres_ranavirus_2012]. The Ranavirus genus of double-stranded DNA viruses [@gray_ecology_2009], affects most amphibian species [@brunner_ranavirus_2015] and host species exhibit a wide range of competence for the parasite [@hoverman_phylogeny_2011]. At the Savannah River Site (South Carolina, USA), a spatially-distributed set of 20 wetlands has been extensively sampled in the context of ranavirus infection over a 6-month period. We focus on larval amphibian communities which are bound by their aquatic habitat but connected through the overland movement of their adult stages [@mihaljevic_parasite_2018]. Ranavirus is transmitted via intra- and interspecific direct transmission, which exhibits a positive, but ultimately saturating, relationship with host abundance [@brunner_heterogeneities_2017]. Additionally, ranavirus can be transmitted environmentally via free-living infectious virions shed into water by infected live individuals or decaying carcasses [@brenes_transmission_2014]. Ranavirus persistence times in water have been found to diminish at high ambient temperatures [@nazir_environmental_2012] suggesting that the relative importance of environmental transmission, versus contact-based transmission, should depend on environmental conditions. We hypothesize that community-scale prevalence of ranavirus will have a positive relationship with host abundance and community competence but a negative relationship with increasing water temperatures.

We begin with a theoretical model, where we use the community basic reproductive number, R0, to estimate the transmission potential of ranavirus in multi-host communities [@dobson_population_2004]. R0 provides a valuable lens into transmission potential, clarifying conditions necessary for parasite invasion and persistence. Calculation of R0 at the community scale explicitly considers the role of community composition in the transmission of a multi-host parasite along with host abundance. In our case it also includes the relative force of infection from free-living infectious virions, versus infected hosts. Multiple transmission routes can increase overall transmission potential, as evidenced by contact and environmental transmission in models of avian influenza virus [@breban_role_2009] and causal agents of diarrheal diseases [@tien_multiple_2010] as well as contact and sexual transmission in models of Ebola transmission [@abbate_potential_2016; @vinson_potential_2016]. From our model, we analyzed the relative contribution of direct and environmental transmission in allowing the parasite to exceed the critical value of R0=1. These two routes are linked because environmental transmission relies on the shedding of viral material from infected individuals and higher environmental transmission rates will generate more opportunities for subsequent direct transmission. Specifically, we determine how transmission from each route facilitates parasite invasion under different scenarios of community composition, host abundance, and virus decay rate (half-life) in water, both as separate factors and acting in concert.

Using empirical data, we then apply metacommunity theory and dimensionality reduction to explain how biotic and abiotic factors contribute to community composition [@leibold_metacommunity_2004], and then we evaluate these communities in their ability to differentially facilitate transmission. Community compositions change over space or time and can include dynamic, predictable patterns of assembly or disassembly [@johnson_community_2019; @ostfeld_community_2003]. These changes in community composition can then influence transmission potential of a parasite and may map to dilution or amplification effects [@luis_species_2018; @north_anthropogenic_2015]. According to theory, a dilution effect may occur whenever hosts vary in competence and reductions in diversity are associated with increases in mean competence [@johnson_why_2015]. In contrast, an amplification effect can occur when increased host diversity causes an increase in mean competence [@keesing_effects_2006]. Considering these conflicting patterns, we relate species evenness, in addition to species richness, as a predictor for both community competence and infection prevalence. In the ranavirus system, we measure competence as a species’ average viral load, which estimates the differential propensity for hosts to generate new infections. While the amphibian community comprises several species, their viral loads are bimodal and communities can be simplified into two groups (high and low competence), which is especially useful in model building and analysis. 

Modeling results show that the effect on R0 by community composition, host abundance, and environmental persistence of virus are independently important such that weak contribution to R0 by a factor can be compensated by appropriately strong contributions from other factors. In addition, we find that each of these factors combined can have an appreciably greater than additive effect, meaning some host communities can be disproportionately at risk of epizootics. The empirical data confirm that outbreaks are frequently associated with ‘perfect storms’ of large communities dominated by competent species at relatively low temperatures. Importantly, neither species richness nor species evenness were found to be powerful predictors for ranavirus prevalence. However, species evenness and community competence emerged as informative metrics for identifying mechanism in the diversity-disease relationship. Our results improve our understanding of the location and timing of outbreaks of multi-host parasites and help to predict when host communities may be most vulnerable, supporting the study of zoonotic diseases by identifying potential disease hot spots that may form due to natural or anthropogenic causes. We contend that the study of abiotic factors directly influencing transmission and indirectly driving community composition holds great promise to advance diversity-disease research.


# Methods

## Transmission Model	

According to known transmission, ranaviruses can infect a wide range of amphibian hosts and infectious periods can range from a few days up to weeks[@gray_ecology_2009]. Transmission can occur both directly and indirectly and exposure appears to induce an adaptive immune response in surviving hosts. Accordingly, we modeled a host community using an SIR framework for each species (Table 1). For model tractability, we limited the community to two host types that could vary in key traits including abundance and competence. As well as facilitating model analysis, this choice also reflects the empirical observation that viral loads of host species are bimodal (Supplementary Figure 1). In addition to intra- and inter-specific direct transmission, we included environmental transmission, whereby infectious host individuals shed virus into the environment where it persists for some finite time and can cause new infections without host-to-host contact [@gray_ecology_2009]. We included host demography via a constant birth rate and a constant per capita mortality rate, resulting in a disease-free equilibrium for each host species given by the ratio of the birth rate and mortality rate. For the model to reflect the viral load-based definition of host competence, infectivity, but not susceptibility, varied between the high and low competence host. This means that the rate of transmission from infectious individuals did not depend on whether transmission was to an intra- or inter-specific host, but rather on the high or low competence status of the infectious animal. For example, a high competence individual is likely to infect many individuals of either species when infectious and a low competence individual is expected to infect fewer individuals. In keeping with the assumption of no difference in host susceptibility between species, the environmental transmission rate was set to be the same for both species. 

Using the next-generation matrix method [@diekmann_definition_1990; @diekmann_construction_2009], we calculated the community basic reproductive number [@dobson_population_2004], hereafter referred to as R0, for our community of hosts to determine the conditions necessary for parasite invasion (R0>1). Consequently, we determined how the boundary R0=1 operates as a function of parameters for communities with varying characteristics, specifically the effects of community composition, total host abundance, and viral half-life. To illustrate these effects, we created a reference community and 4 manipulated communities that were designed to make the communities more suitable for parasite invasion. The reference community had an equal number of both species, a total host abundance of 150 individuals, and a viral half-life of 1.35 days. The composition-manipulated community was altered to be dominated by the more competent species by a ratio of 2:1. The abundance-manipulated community was altered only in abundance, to a value of 175 individuals, and the half-life-manipulated community was altered by doubling the viral half-life to 2.7 days. The final manipulated community combined each of these single-factor manipulations. For each community, we calculated R0 over a range of values for environmental and contact transmission rates of the more competent species while holding the contact transmission rate for the less competent species constant. This allowed us to characterize the extent to which parasite invasion was more likely, i.e., occurring for an increased set of transmission parameters that included combinations previously associated with failure to invade (R0<1). 

## Data Collection and Calculation of Community Competence

All empirical data were previously collected [@coleman_incorporating_2018] at the Savannah River Site (South Carolina, USA). 20 wetlands were sampled monthly for 6 months from February to July in 2016 at the Savannah River Site. Of the 120 sampling events, 96 produced data, with the others being discounted due to wetlands being dry at the time of sampling. Each sampling event included an estimate of larval amphibian abundance ascertained from minnow traps and dip-net sweeps around the perimeter and center of the wetland. In addition to abundance, a single individual per species was collected per dip-net sweep or minnow trap. These individuals were tested for ranavirus load using qPCR in triplicate which were averaged to determine the viral load for an individual. At the species-level, all individuals that were analyzed for viral load were then averaged to provide a species level estimate of viral load, which was used as a proxy for competence. Using species-level competence, we then calculated community competence as the weighted average of each species’ competence, with weights given by the relative abundance of each species. Each site-month combination was treated as a distinct community in these calculations. Empirical data on community composition, viral loads, and infection prevalence enabled us to analyze host communities according to their community competence and relate these to diversity metrics, as detailed below.

## Host Community Analysis

First, using a metacommunity framework, we created a site-by-species matrix that included species presence or absence, and where ‘site’ referred to a unique wetland-month combination, referred to herein as a community. Within this matrix, communities were ordinated by minimizing the number of embedded absences and were then tested for key metacommunity patterns including nestedness and block replacement using the “metacom” package in R [@dallas_metacom_2014; @leibold_coherence_2002]. Following this, we used principal component analysis to order communities according to their similarity in community composition. We did this by ranking each community according to the score of their first principal component (PC1), which captured 71% of the variance. We then used this list of ranked communities to ascertain the congruence between host community composition and community competence, testing the assumption that similarly composed communities will be similarly competent. We used a generalized additive model with a geo-additive term to test the relationship between community competence and time (sampling month), space (wetland coordinates), and host abundance to establish the effects of these variables on community competence.

Following this, we treated community competence and infection prevalence as separate response variables and used species richness and species evenness as predictor variables. Community competence is used to measure an instantaneous property of the community in terms of its propensity to support a parasite, but infection prevalence is expected to manifest after sufficient transmission has occurred and so was lagged by a month (the period of time between measurements and a plausible estimate of the parasite generation time [@brunner_testing_2009]). We estimated infection prevalence for the community by combining the observed host abundances and the raw infection prevalence of individual host organisms that were sampled for parasite presence using qPCR. The sampled hosts provided a percentage for each species that were found to be infected and this percentage was then weighted by the observed abundance of that species in that community. Species richness was calculated as the sum of unique species present and species evenness was measured by Pielou’s J [@pielou_interpretation_1984]. Species richness was used to test if basic patterns of assembly and disassembly were able to predict transmission potential via dilution or amplification effects, whereas species evenness was used to detect if relative abundances of species were controlling transmission via community competence. In an effort to more closely examine the effects of species evenness on community competence, we ordered sites according to community competence and identified trends in the relative abundance of species and the phylogenetic relationships of our host species. We expected phylogenetically clustered or overdispersed species to co-occur less frequently, and we additionally determined the extent to which competence was clustered (versus dispersed) within the phylogeny so that we could evaluate the extent to which multiple competent species may co-occur and potentially dominate a community. Finally, we tested for statistically significant relationships between infection prevalence and community competence, abundance, and mean water temperature using both multivariate (generalized linear model) and univariate tests (Spearman Rank correlation test with a correction for multiple comparisons). Mean water temperature was included to serve as a proxy for environmental persistence time of free-living infectious virions; as mean water temperature increases the viral half-life is expected to decrease [@nazir_environmental_2012].


# Results

## Transmission Model

Model analysis determined the criteria for an epizootic to occur (R0>1) (Figure 1). In the relative transmission rate space (Figure 1), each community exhibits minimum conditions for invasion (R0=1, contour lines). The linear shape of each line indicates that the direct and environmental transmission routes are always substitutive; a reduction in one parameter can be compensated by a proportional increase in the other. However, increasing each factor (Figure 1; A: proportion of high-competence hosts=red line, B: total host abundance=gold line, C: viral half-life=green line) affects the invasion contour differently when compared to the reference, reflecting differences in which transmission route can better tolerate a reduction while still allowing parasite invasion in the altered community. When community composition is altered to an increased proportion of the highly competent species, the slope of the invasion threshold is reduced relative to the reference community, meaning that contact transmission can be reduced appreciably while maintaining R0>1 (Figure 1A; red vs. gray line). However, when viral half-life is increased, it is environmental transmission that can be reduced to a greater extent (Figure 1C; green vs. gray line). Increasing total host abundance does not change the slope of the invasion threshold, but does reduce the x- and y-intercept, meaning both transmission rates can be lowered while maintaining R0>1, but neither rate is more impactful than the other (Figure 1B; gold vs. gray line). Finally, when all manipulations are combined, there is a lowering of the invasion threshold that exceeds the changes of any condition alone, indicating synergistic interaction between factors affecting overall transmission potential (Figure 1D; purple vs. gray line). 

## Host Community Analysis

Using the sampling unit of community (a unique wetland-month combination), metacommunity analysis revealed a block-replacement pattern, meaning groups of species tended to turn over together across communities (coherence: P < 0.00001; turnover: P < 0.00001; boundary clumping: P < 0.00001; Supplementary Figure 2). When ordinated according to community composition using rank order along PC1 we found that similar communities exhibited similar values of community competence (Figure 2). Additionally, we note that communities of different compositions had similar values for community competence (e.g., Figure 2, communities ranked ~5 and ~30) in keeping with the fact that several combinations of weighted competence scores can evaluate to the same community competence. Analysis of the relationship between community competence and the predictors of sampling month, wetland coordinates, and host abundance using a generalized additive model revealed significant effects for sampling month (P < 0.00001) and host abundance (P < 0.0001) but not for wetland coordinates (P = 0.34). Overall, communities with higher values of competence occurred in February through May, whereas in June and July, several communities showed low values of community competence (Supplementary Figure 3a). In terms of absolute host abundance, both high and low values could result in high community competence (Figure 2, shape size), but the trend was generally positive (Supplementary Figure 3b). While temperature is predicted to influence environmental transmission via viral half-life, community structure is not strongly dictated by temperature (Figure 2, color); air and water temperature at sites align with PC2, which explained 26% of the variance (Supplementary Figure 4).

Using evenness as our predictor variable, we found that community competence had a bimodal relationship at low evenness that converged at higher evenness (Figure 3). At low evenness, communities were generally found to have either high or low values of community competence with only a few communities exhibiting moderate values of community competence. At higher values of evenness (Pielou’s J > 0.6), most communities had either low or moderate values of community competence. Intuitively, we expected higher evenness communities to have moderate values of community competence because our set of species were made up of both high and low competence hosts. However, at lower evenness, the competence of dominant species will drive community competence which led to the bimodal relationship.  Furthermore, we found that communities of low evenness and high community competence were generally of higher abundance and had higher future infection prevalence. There were also exceptions to this pattern where communities with low or moderate community competence still had high future infection prevalence. This can be caused by high host abundance driving transmission in some communities (Figure 3; i and ii) or low sample size resulting in relatively high infection prevalence in others (Figure 3). When ordered by community competence, we found that the most competent communities were dominated by either one or a few highly competent species (Figure 4). In the phylogeny, we see that these highly competent species are moderately dispersed, suggesting that limiting similarity may not be hindering coexistence (Figure 4, bottom panel; Supplementary Figure 6).

Finally, we found that community competence and host abundance correlated positively with prevalence while mean water temperature correlated negatively with prevalence. In separate univariate analyses when using a Spearman rank correlation test we found significant results for community competence (P < 0.0001; figure 5), abundance (P < 0.01; figure 5), and mean water temperature (P = 0.021; figure 5) after adjusting for multiple comparisons using the “Holm” method [@aickin_adjusting_1996; @holm_simple_1979]. Due to the inherently noisy data on parasite prevalence, a multivariate model that predicted infection prevalence in response to community competence, total host abundance, and mean water temperature was not able to detect any significant relationships. Overall, these results suggest that the prevalence of ranavirus in a community may be driven by multiple factors working in conjunction and support our predictions regarding the directional effects of community competence, host abundance, and virus half-life (Figure 5). Species richness was not predictive of infection prevalence meaning we did not detect a classic dilution effect pattern given by a negative relationship; rather the non-significant trend was slightly positive (Supplementary Figure 5; Spearman’s rho = 0.15, P = 0.14).


# Discussion

Using a blend of theoretical model predictions and empirical data, we have shown that the effects of host abundance, community composition, and the environment can simultaneously affect the transmission potential of a generalist parasite in communities of hosts. In our mathematical model, we demonstrated that these independent factors can all enhance transmission and that when combined, can have a more than additive effect. Using empirical data, we confirmed that both biotic and abiotic factors can have detectable effects on parasite transmission at an intermediate spatial scale. Importantly, we also found that species evenness was a more informative predictor for parasite transmission potential compared to species richness. Moreover, our results inform the risk of amphibian communities to ranavirus epizootics and extend theory regarding the relationship between biodiversity and the transmission of generalist parasites by including environmental transmission and the factors that promote it.

 From our theoretical model, we learned that the inclusion of both contact-based and environmental transmission allowed for each transmission mode to compensate for the other; a low strength of one transmission mode could be supplemented by the other transmission mode, resulting in a broader range of favorable conditions for the parasite [@vinson_potential_2016]. In other studies, it has been noted that the incorporation of environmental transmission can provide dramatically different estimates of R0 and allow for persistence of parasites at population sizes that would not be supported by contact transmission alone [@breban_role_2009; @breban_general_2010; @tien_multiple_2010]. We build upon these findings by demonstrating how the relative strength of transmission modes can emphasize the importance of different factors relevant to parasite transmission. In a community where the strength of contact-based transmission is high and environmental transmission strength is low we expect community composition to have a significant impact on transmission. Conversely, when environmental transmission is high and contact-based transmission is low, we expect community composition to be less important for overall transmission. This suggests that in natural systems where both modes of transmission are available, the influence of both may be present but obscured by the other. When we enhanced absolute host abundance, we anticipated that contact-based transmission would be favored, but our analysis showed that the increase in available hosts can augment both transmission modes equally. We understood this to be because as the number of hosts increases, the quantity of free-living infectious virions also increases proportionally due to a greater number of infected hosts shedding viral material as well as simply increasing host density. This results in an increase in the force of infection for both contact-based transmission and environmental transmission. 

From the empirical data, we found that community composition and evenness were far more informative in predicting transmission potential compared to species richness, in spite of the fact that the diversity-disease literature includes many correlative studies that investigate the relationship between species richness and infection prevalence. Indeed, recent research has emphasized the importance of a more mechanistic understanding of diversity-disease relationships, and host species evenness may aid in this effort [@merrill_towards_2020; @rohr_towards_2019]. Evenness, rather than richness, can more directly relate the composition of a community to its transmission potential. At low evenness, the identity of the dominant species drives community competence, and we found that communities with the highest absolute abundance were usually of lower evenness and dominated by a few highly competent species. This pattern is supported in theory connecting life history traits to host competence, where hosts with a faster pace-of-life invest heavily into rapid growth and reproduction and less into immunity, resulting in highly abundant, highly competent hosts [@joseph_does_2013]. Together, host abundance, evenness, and community competence have the potential to offer a more mechanistic lens into community compositions and how they will affect infection prevalence.

Detection of diversity-disease relationships is facilitated by predictable community structures [@faust_null_2017]. Classic dilution-effect systems typically operate by nested structures influencing parasite transmission through biodiversity loss [@logiudice_ecology_2003]. In these examples, species losses follow a pattern where less competent hosts are lost before more competent hosts [@johnson_biodiversity_2013]. In contrast, our study revealed block-replacement of sets of host species, where transmission potential was not changing due to species richness, but rather by species evenness and identity; often, ranavirus attained high prevalence due to correlated competence and abundance of certain key species. However, the generality of this depends on how competence is typically distributed among a community of host species and how relationships among those species affect their probability of co-occurring and abundance. The amphibian species in our study showed evidence of phylogenetic repulsion and environmental filtering, as has been detected, for example, in avian communities [@weinstein_role_2017]. When co-occurring, species that were closely related or distantly related to their neighbors had low relative abundance (Supplementary Figure 6). In contrast, species that were intermediately related to others on average attained high relative abundance. Combined with the fact that high competence was a relatively well-dispersed trait in the studied amphibian clade, this created the conditions for competent species to co-occur and attain high relative abundance. By corollary, if competent species were clustered phylogenetically, then high community competence would be enhanced by the presence of an environmental filter and absence of phylogenetic repulsion. Future work may benefit from considering host communities simultaneously in terms of the rules that govern species co-occurrence and abundance and the distribution of competence levels among those species.

The study of individual host competence and how it scales to a community can provide us with valuable insight into how well host communities can support generalist parasites [@becker_beyond_2020]. However, host competence can be a challenging trait to measure because it is multifactorial, relying on components such as exposure, susceptibility, suitability, and transmissibility [@downs_scaling_2019]. In our study, we use mean viral load as a proxy for host competence which is useful because it informs shedding rate, infectivity, and host suitability. However, viral load is not a holistic measure of host competence because it does not address, for example, the infectious period or susceptibility. Further research on host competence should incorporate more robust measures of competence such as those derived from controlled infection assays [@merrill_variation_2019]. Factors within host species such as age and sex will also likely change the competence of a host and while there may be the ability to measure competence with genetic methods, there is likely to be phenotypic plasticity within the trait [@gervasi_context_2015]. 

Ranaviruses in amphibians are a useful and important system for studying diversity-disease relationships because of their highly generalist nature and role in global amphibian biodiversity declines [@lesbarreres_ranavirus_2012; @north_anthropogenic_2015]. Environmental transmission of ranavirus and the connection of wetlands by amphibian adults made this system especially useful for our study of the effects of host composition, host abundance, and environmental factors. However, these features are not limited to this study system and other multi-host generalist parasite systems can benefit from our findings. Furthermore, our research focused on natural variations in biodiversity, but it is important to recognize how anthropogenic influence will alter these patterns as well [@altizer_climate_2013; @rohr_frontiers_2011]. Amphibian species, in particular, have been extremely sensitive to anthropogenic disturbance and have been considered proxies for overall environmental health [@scheele_amphibian_2019]. Land use and climate change are also factors that affect amphibian communities globally and it is important to understand the implications of these changes [@wilkinson_habitat_2018]. Altogether, the ecology of ranavirus in amphibians and the global relevance of amphibian biodiversity make this system a valuable case study for the joint influence of biotic and abiotic factors on parasite transmission under natural and artificial settings. 

By focusing on parasites with multiple transmission modes, we have highlighted how biotic or abiotic factors may differentially exacerbate the impact of parasites introduced into a host community. In addition, we have expanded theory regarding diversity-disease relationships to advocate the use of species evenness and community competence as informative predictors for the impact of generalist parasites in multi-host communities. These metrics can facilitate analysis that is more focused on the mechanics of dilution or amplification rather than correlative association between disease presence and underlying assembly rules that may be inconsistent across systems, space, and time. Furthermore, we advocate for deeper analysis of host community phylogeny in the context of diversity-disease relationships which can provide insight into patterns of host species co-occurrence and host traits that may correlate with competence. Together, these developments combined with the contextual understanding of specific host-parasite ecology should allow for mechanistic understanding of many generalist parasite systems.


# References

